//js modules
import "./module/headerInvert";
import "./module/morebtn";
import "./module/hamburger";
import "./module/loader";
import "./module/textAnim";
import "./module/targetInview";
import "./module/timeline";
import "./module/pageTtlAnim";
import "./module/worksListFade";