//js modules
import "./module/headerInvert";
import "./module/morebtn";
import "./module/hamburger";
import "./module/countUp";
import "./module/loader";
import "./module/currentYear";
import "./module/textAnim";
import "./module/targetInview";
import "./module/timeline";